name: Reddit Watcher

on:
  schedule:
    # Run every 15 minutes (GitHub Actions free tier minimum)
    - cron: '*/15 * * * *'
  workflow_dispatch: # Allow manual triggering

jobs:
  monitor:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Configure git
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git

      - name: Run Reddit monitor
        env:
          REDDIT_CLIENT_ID: ${{ secrets.REDDIT_CLIENT_ID }}
          REDDIT_CLIENT_SECRET: ${{ secrets.REDDIT_CLIENT_SECRET }}
          REDDIT_USER_AGENT: ${{ secrets.REDDIT_USER_AGENT }}
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          NOTIFICATION_EMAIL: ${{ secrets.NOTIFICATION_EMAIL }}
          SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          KEYWORDS: ${{ secrets.KEYWORDS }}
          CHECK_INTERVAL_MINUTES: ${{ secrets.CHECK_INTERVAL_MINUTES }}
          MAX_POSTS_PER_RUN: ${{ secrets.MAX_POSTS_PER_RUN }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          GITHUB_ACTIONS: true
        run: python main.py

      - name: Commit updated seen posts
        run: |
          if [ -f seen_posts.json ]; then
            if git diff --quiet seen_posts.json; then
              echo "No changes to seen_posts.json"
            else
              git add seen_posts.json
              git commit -m "Update seen posts - $(date -u '+%Y-%m-%d %H:%M:%S') UTC"
              git push
            fi
          else
            echo "seen_posts.json not found"
          fi
        if: always()

      - name: Upload logs (for debugging)
        uses: actions/upload-artifact@v4
        with:
          name: logs-${{ github.run_number }}
          path: reddit_monitor.log
          retention-days: 7
        if: failure() # Only upload logs on failure
