name: Reddit Watcher

on:
  schedule:
    # Run every 15 minutes (GitHub Actions free tier minimum)
    - cron: '*/15 * * * *'
  workflow_dispatch:  # Allow manual triggering

jobs:
  monitor:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Download previous seen posts
      uses: actions/download-artifact@v3
      with:
        name: seen-posts
        path: .
      continue-on-error: true  # Don't fail if artifact doesn't exist yet
      
    - name: Run Reddit monitor
      env:
        REDDIT_CLIENT_ID: ${{ secrets.REDDIT_CLIENT_ID }}
        REDDIT_CLIENT_SECRET: ${{ secrets.REDDIT_CLIENT_SECRET }}
        REDDIT_USER_AGENT: ${{ secrets.REDDIT_USER_AGENT }}
        EMAIL_USER: ${{ secrets.EMAIL_USER }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        NOTIFICATION_EMAIL: ${{ secrets.NOTIFICATION_EMAIL }}
        SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
        SMTP_PORT: ${{ secrets.SMTP_PORT }}
        KEYWORDS: ${{ secrets.KEYWORDS }}
        CHECK_INTERVAL_MINUTES: ${{ secrets.CHECK_INTERVAL_MINUTES }}
        MAX_POSTS_PER_RUN: ${{ secrets.MAX_POSTS_PER_RUN }}
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        GITHUB_ACTIONS: true
      run: python main.py
      
    - name: Upload seen posts
      uses: actions/upload-artifact@v3
      with:
        name: seen-posts
        path: seen_posts.json
        retention-days: 30  # Keep for 30 days
      if: always()  # Upload even if the script fails
      
    - name: Upload logs
      uses: actions/upload-artifact@v3
      with:
        name: logs-${{ github.run_number }}
        path: reddit_monitor.log
        retention-days: 7  # Keep logs for 7 days
      if: always()  # Upload even if the script fails